### ISSUE TITLE
renderSettings Error

### ISSUE THREAD

**Issue by danimrath** [deidril/sfrpg-pdf-en-import#18]
When loading a SF1e world even a fresh one it throws the following error and none of the actors get the art.

Error thrown in hooked function '' for hook 'renderSettings'. _0x147a31[_0x1f003c(...)] is not a function

I have tried on older versions of the starfinder system with a fresh install and fresh world. 

I have tried uninstalling the module and re-installing.

Windows 11

I was on Foundry 13.350 and tried also after updating to 13.351
